openapi: "3.0.0"
info:
  version: 1.0.0
  title: Blockchain Services
  contact:
    name: Amogh Kulkarni
    email: amoghcoolkarni983@gmail.com
paths:
  /blocks:
    get:
      summary: List all blocks
      operationId: listBlocks
      tags:
        - blocks
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of blocks
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Blocks"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Block:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Blocks:
      type: array
      items:
        $ref: "#/components/schemas/Block"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string